import type { Agent, LogEntry } from '@/types/agent'

const now = new Date()
const ago = (mins: number) => new Date(now.getTime() - mins * 60000).toISOString()

export const mockAgents: Agent[] = [
  {
    id: 'agt-001',
    name: 'Architect Alpha',
    type: 'code',
    status: 'running',
    goal: 'Scaffold the Agentic OS frontend — create all component files, configure Tailwind, set up routing and store architecture.',
    currentTask: 'Writing AgentLogStream.tsx with virtualized scroll',
    spawnedAt: ago(64),
    lastActiveAt: ago(0.1),
    uptimeSeconds: 3842,
    toolCallCount: 47,
    memoryReads: 12,
    memoryWrites: 3,
    model: 'claude-sonnet-4-6',
    pid: 18432,
    taskSteps: [
      { id: 's1', label: 'Scaffold Vite project', status: 'done', startedAt: ago(64), completedAt: ago(60) },
      { id: 's2', label: 'Install dependencies', status: 'done', startedAt: ago(60), completedAt: ago(55) },
      { id: 's3', label: 'Configure Tailwind & theme', status: 'done', startedAt: ago(55), completedAt: ago(48) },
      { id: 's4', label: 'Write type definitions', status: 'done', startedAt: ago(48), completedAt: ago(42) },
      { id: 's5', label: 'Build UI primitives', status: 'done', startedAt: ago(42), completedAt: ago(30) },
      { id: 's6', label: 'Build agent components', status: 'active', startedAt: ago(30) },
      { id: 's7', label: 'Build spawn panel', status: 'pending' },
      { id: 's8', label: 'Wire routing & pages', status: 'pending' },
    ],
  },
  {
    id: 'agt-002',
    name: 'Researcher Beta',
    type: 'research',
    status: 'idle',
    goal: 'Research best practices for multi-agent orchestration frameworks, WebSocket state sync patterns, and Obsidian plugin API for memory integration.',
    currentTask: undefined,
    spawnedAt: ago(120),
    lastActiveAt: ago(15),
    uptimeSeconds: 7200,
    toolCallCount: 83,
    memoryReads: 41,
    memoryWrites: 19,
    model: 'claude-sonnet-4-6',
    taskSteps: [
      { id: 's1', label: 'Research agent frameworks', status: 'done' },
      { id: 's2', label: 'Document WebSocket patterns', status: 'done' },
      { id: 's3', label: 'Analyze Obsidian API', status: 'done' },
      { id: 's4', label: 'Write synthesis report', status: 'done' },
    ],
  },
  {
    id: 'agt-003',
    name: 'Orchestrator-1',
    type: 'orchestrator',
    status: 'error',
    goal: 'Coordinate Alpha and Beta agents — assign tasks, monitor progress, handle dependencies between agents.',
    currentTask: 'Waiting for agent health check',
    spawnedAt: ago(45),
    lastActiveAt: ago(8),
    uptimeSeconds: 2700,
    toolCallCount: 12,
    memoryReads: 5,
    memoryWrites: 2,
    model: 'claude-opus-4-7',
    errorMessage: 'Subprocess timeout after 30s — agent Alpha health check failed. Retrying in 60s.',
    taskSteps: [
      { id: 's1', label: 'Initialize agent registry', status: 'done' },
      { id: 's2', label: 'Assign tasks to sub-agents', status: 'done' },
      { id: 's3', label: 'Monitor progress loop', status: 'failed' },
    ],
  },
  {
    id: 'agt-004',
    name: 'Ghost Protocol',
    type: 'custom',
    status: 'stopped',
    goal: 'Run nightly security audit of codebase — check for vulnerable dependencies, analyze API endpoints, generate report.',
    currentTask: undefined,
    spawnedAt: ago(480),
    lastActiveAt: ago(360),
    uptimeSeconds: 7200,
    toolCallCount: 156,
    memoryReads: 0,
    memoryWrites: 0,
    model: 'claude-haiku-4-5-20251001',
    taskSteps: [
      { id: 's1', label: 'Dependency audit', status: 'done' },
      { id: 's2', label: 'API surface analysis', status: 'done' },
      { id: 's3', label: 'Generate security report', status: 'done' },
    ],
  },
  {
    id: 'agt-005',
    name: 'Deploy Scout',
    type: 'code',
    status: 'spawning',
    goal: 'Set up CI/CD pipeline — configure GitHub Actions workflows for test, build, and deploy stages.',
    currentTask: 'Initializing environment...',
    spawnedAt: ago(0.5),
    lastActiveAt: ago(0.5),
    uptimeSeconds: 30,
    toolCallCount: 0,
    memoryReads: 0,
    memoryWrites: 0,
    model: 'claude-sonnet-4-6',
    taskSteps: [
      { id: 's1', label: 'Initialize workspace', status: 'active' },
      { id: 's2', label: 'Configure test workflow', status: 'pending' },
      { id: 's3', label: 'Configure deploy workflow', status: 'pending' },
    ],
  },
]

export const mockLogs: LogEntry[] = [
  { id: 'l1', agentId: 'agt-001', level: 'info', message: 'Agent initialized with model claude-sonnet-4-6', timestamp: ago(64) },
  { id: 'l2', agentId: 'agt-001', level: 'tool', message: 'Bash("npm create vite@latest agentic-os -- --template react-ts")', timestamp: ago(63) },
  { id: 'l3', agentId: 'agt-001', level: 'info', message: 'Project scaffolded successfully in ./agentic-os', timestamp: ago(63) },
  { id: 'l4', agentId: 'agt-001', level: 'tool', message: 'Bash("npm install zustand @tanstack/react-query react-router-dom axios lucide-react framer-motion react-virtuoso zod clsx tailwind-merge date-fns")', timestamp: ago(60) },
  { id: 'l5', agentId: 'agt-001', level: 'info', message: 'All 10 packages installed. 0 vulnerabilities.', timestamp: ago(58) },
  { id: 'l6', agentId: 'agt-001', level: 'tool', message: 'Write("src/index.css") → 142 lines written', timestamp: ago(55) },
  { id: 'l7', agentId: 'agt-001', level: 'tool', message: 'Write("src/types/agent.ts") → 45 lines written', timestamp: ago(54) },
  { id: 'l8', agentId: 'agt-001', level: 'tool', message: 'Write("src/types/api.ts") → 38 lines written', timestamp: ago(54) },
  { id: 'l9', agentId: 'agt-001', level: 'warn', message: 'tsconfig.app.json missing path aliases — applying fix', timestamp: ago(53) },
  { id: 'l10', agentId: 'agt-001', level: 'tool', message: 'Edit("tsconfig.app.json") → added baseUrl and paths', timestamp: ago(53) },
  { id: 'l11', agentId: 'agt-001', level: 'info', message: 'Phase 1 complete. Starting Phase 2: UI primitives.', timestamp: ago(48) },
  { id: 'l12', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/ui/Button.tsx")', timestamp: ago(45) },
  { id: 'l13', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/ui/Card.tsx")', timestamp: ago(44) },
  { id: 'l14', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/ui/Badge.tsx")', timestamp: ago(43) },
  { id: 'l15', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/ui/Modal.tsx")', timestamp: ago(42) },
  { id: 'l16', agentId: 'agt-001', level: 'info', message: 'Phase 2 complete. Starting Phase 3: agent components.', timestamp: ago(30) },
  { id: 'l17', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/agents/AgentCard.tsx")', timestamp: ago(28) },
  { id: 'l18', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/agents/AgentList.tsx")', timestamp: ago(25) },
  { id: 'l19', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/agents/AgentDetail.tsx")', timestamp: ago(20) },
  { id: 'l20', agentId: 'agt-001', level: 'info', message: 'Working on AgentLogStream — setting up react-virtuoso integration...', timestamp: ago(5) },
  { id: 'l21', agentId: 'agt-001', level: 'debug', message: 'Virtuoso ref initialized. Auto-scroll threshold: 100px from bottom.', timestamp: ago(3) },
  { id: 'l22', agentId: 'agt-001', level: 'tool', message: 'Write("src/components/agents/AgentLogStream.tsx") → in progress', timestamp: ago(1) },
]
